function createDistanceHistogramWithInset(X, Y)
%CREATEFIGURE(X, Y)
% X = dist_C * scale_to_um_factor (bin 2x2x gives 1um, extra downsampling 2x gives 2um/px)
% Y = dist_N/sum(dist_N)*100 in Occurence, %

%  Auto-generated by MATLAB on 18-Oct-2016 02:47:55

% Create figure
figure1 = figure;

% Create axes
axes1 = axes('Parent',figure1,...
    'Position',[0.0928571428571429 0.135714285714286 0.812142857142857 0.789285714285715]);
hold(axes1,'on');

% Create plot
plot(X,Y,'Parent',axes1,'Marker','o');

% Create xlabel
xlabel('Distance between cells, \mum');

% Create ylabel
ylabel('Occurence, %');

box(axes1,'on');
% Create axes
axes2 = axes('Parent',figure1,...
    'Position',[0.525 0.528571428571429 0.380357142857143 0.397619047619049]);
hold(axes2,'on');

% Create plot
plot(X,Y,'Parent',axes2,'Marker','o');

% Create xlabel
xlabel('Distance between cells, \mum');

% Create ylabel
ylabel('Occurence, %');

%% Uncomment the following line to preserve the X-limits of the axes
xlim(axes2,[0 90]);
box(axes2,'on');
